### ISSUE TITLE
Plugin issue

### ISSUE THREAD

**Issue by Pattyx** [Lerg/plugins-sample-qrscanner#2]
it is giving an error that plugin.qrscanner is not present
WARNING: plugin.qrscanner is not configured in build.settings
WARNING: The 'plugin.qrscanner' library is not available on this platform.

**Comment by Pattyx** [comment]
what can i do for this??

**Comment by Lerg** [comment]
Make sure you've activated the plugin for your Corona account and that you are using iOS or Android. The "not available on this platform" message appears on macOS and Windows.

**Comment by Pattyx** [comment]
How can i activate the plugin in my corona account???

**Comment by Pattyx** [comment]
how can i activate the plugin in my corona sdk??

**Comment by Lerg** [comment]
Go to Corona Marketplace https://marketplace.coronalabs.com/, use your account to purchase the plugin. Then Corona Simulator would see that you have the plugin (giving that you use the same account on the website and in Corona Simulator). And when you build for iOS or Android, the plugin will be bundled with your application.
